# Generated by Django 5.2.1 on 2026-05-30 03:49

import apps.administrativo.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=180, unique=True)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('documento_identidad', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', apps.administrativo.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estudiantes_grupos',
            },
        ),
        migrations.CreateModel(
            name='GrupoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('periodo_academico', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(related_name='grupos_estudiante', through='administrativo.EstudianteGrupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupos_academicos',
            },
        ),
        migrations.AddField(
            model_name='estudiantegrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.grupoacademico'),
        ),
        migrations.CreateModel(
            name='PermisoPorRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.permiso')),
            ],
            options={
                'db_table': 'permisos_por_rol',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado'], name='usuarios_estado_7877c9_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['apellidos', 'nombres'], name='usuarios_apellid_d1c56e_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoacademico',
            index=models.Index(fields=['docente'], name='grupos_acad_docente_98f22e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grupoacademico',
            unique_together={('nombre', 'periodo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiantegrupo',
            unique_together={('estudiante', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='permisoporrol',
            unique_together={('rol', 'permiso')},
        ),
    ]
