# Generated by Django 5.2.1 on 2026-05-30 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_decision', models.TextField()),
                ('consecuencia', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ADECUADA', 'Adecuada'), ('RIESGOSA', 'Riesgosa'), ('INADECUADA', 'Inadecuada'), ('NEUTRA', 'Neutra')], default='NEUTRA', max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('requiere_justificacion', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'decisiones',
                'ordering': ('escena_origen', 'orden'),
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tematicas',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField()),
                ('contexto', models.TextField(blank=True)),
                ('objetivos_aprendizaje', models.TextField(blank=True)),
                ('advertencia_contenido', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('BASICO', 'Basico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('max_intentos', models.PositiveIntegerField(default=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_creados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'casos',
            },
        ),
        migrations.CreateModel(
            name='AsignacionCaso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_hechas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.grupoacademico')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.caso')),
            ],
            options={
                'db_table': 'asignaciones_casos',
            },
        ),
        migrations.CreateModel(
            name='ActorCaso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160)),
                ('rol_en_caso', models.CharField(blank=True, max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('es_sensible', models.BooleanField(default=False)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actores', to='simulador.caso')),
            ],
            options={
                'db_table': 'actores_caso',
            },
        ),
        migrations.CreateModel(
            name='CasoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.competencia')),
            ],
            options={
                'db_table': 'casos_competencias',
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='competencias',
            field=models.ManyToManyField(blank=True, through='simulador.CasoCompetencia', to='simulador.competencia'),
        ),
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.competencia')),
            ],
            options={
                'db_table': 'criterios_rubrica',
            },
        ),
        migrations.CreateModel(
            name='DecisionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impacto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.competencia')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.decision')),
            ],
            options={
                'db_table': 'decisiones_competencias',
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='competencias',
            field=models.ManyToManyField(blank=True, through='simulador.DecisionCompetencia', to='simulador.competencia'),
        ),
        migrations.CreateModel(
            name='Escena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=220)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('INTRODUCCION', 'Introduccion'), ('DESARROLLO', 'Desarrollo'), ('DECISION', 'Decision'), ('USO_HERRAMIENTA', 'Uso de herramienta'), ('RETROALIMENTACION', 'Retroalimentacion'), ('FINAL', 'Final')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='simulador.caso')),
            ],
            options={
                'db_table': 'escenas',
                'ordering': ('caso', 'orden'),
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='escena_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simulador.escena'),
        ),
        migrations.AddField(
            model_name='decision',
            name='escena_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='simulador.escena'),
        ),
        migrations.CreateModel(
            name='CasoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.etiqueta')),
            ],
            options={
                'db_table': 'casos_etiquetas',
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, through='simulador.CasoEtiqueta', to='simulador.etiqueta'),
        ),
        migrations.CreateModel(
            name='EvaluacionIntento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacion_general', models.TextField(blank=True)),
                ('evaluada_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluaciones_intentos',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentario', models.TextField(blank=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.criteriorubrica')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='simulador.evaluacionintento')),
            ],
            options={
                'db_table': 'evaluaciones_criterios',
            },
        ),
        migrations.CreateModel(
            name='HerramientaProfesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('plantilla_json', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'herramientas_profesionales',
            },
        ),
        migrations.CreateModel(
            name='HerramientaPorCaso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligatoria', models.BooleanField(default=False)),
                ('condicion_uso', models.TextField(blank=True)),
                ('parametros_json', models.JSONField(blank=True, default=dict)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.escena')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.herramientaprofesional')),
            ],
            options={
                'db_table': 'herramientas_por_caso',
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_intento', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado'), ('PENDIENTE_CIERRE', 'Pendiente de cierre'), ('CANCELADO', 'Cancelado')], default='EN_PROGRESO', max_length=30)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.asignacioncaso')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.caso')),
                ('escena_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intentos',
            },
        ),
        migrations.CreateModel(
            name='IndicadorDesempeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_indicador', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.competencia')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.intento')),
            ],
            options={
                'db_table': 'indicadores_desempeno',
            },
        ),
        migrations.AddField(
            model_name='evaluacionintento',
            name='intento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulador.intento'),
        ),
        migrations.CreateModel(
            name='ComparacionIntento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diferencias_json', models.JSONField(blank=True, default=dict)),
                ('recomendaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.caso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('intento_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_a', to='simulador.intento')),
                ('intento_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_b', to='simulador.intento')),
            ],
            options={
                'db_table': 'comparaciones_intentos',
            },
        ),
        migrations.CreateModel(
            name='ComentarioDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('visible_estudiante', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_docente', to='simulador.intento')),
            ],
            options={
                'db_table': 'comentarios_docente',
            },
        ),
        migrations.CreateModel(
            name='BitacoraReflexiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflexion', models.TextField()),
                ('aprendizaje_clave', models.TextField(blank=True)),
                ('consideraciones_eticas', models.TextField(blank=True)),
                ('autocuidado', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='simulador.intento')),
            ],
            options={
                'db_table': 'bitacoras_reflexivas',
            },
        ),
        migrations.CreateModel(
            name='AlertaDesempeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BAJO_DESEMPENO', 'Bajo desempeno'), ('EVENTO_CRITICO', 'Evento critico'), ('RIESGO_ALTO', 'Riesgo alto'), ('INACTIVIDAD', 'Inactividad')], max_length=30)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('REVISADA', 'Revisada'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('umbral_configurado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_observado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_estudiante', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.competencia')),
                ('intento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.intento')),
            ],
            options={
                'db_table': 'alertas_desempeno',
            },
        ),
        migrations.CreateModel(
            name='InteraccionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('dentro_alcance', models.BooleanField(default=True)),
                ('bloqueo_por_respuesta_correcta', models.BooleanField(default=False)),
                ('metadatos_json', models.JSONField(blank=True, default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.caso')),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('intento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.intento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interacciones_ia',
            },
        ),
        migrations.CreateModel(
            name='ProgresoEscena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.escena')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='simulador.intento')),
            ],
            options={
                'db_table': 'progreso_escenas',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoria'), ('GUIA', 'Guia'), ('LECTURA', 'Lectura'), ('VIDEO', 'Video'), ('INSTRUMENTO', 'Instrumento'), ('OTRO', 'Otro')], max_length=20)),
                ('resumen', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True)),
                ('referencia_bibliografica', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='RecursoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_antes', models.BooleanField(default=True)),
                ('visible_durante', models.BooleanField(default=True)),
                ('visible_despues', models.BooleanField(default=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.competencia')),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.recurso')),
            ],
            options={
                'db_table': 'recursos_casos',
            },
        ),
        migrations.CreateModel(
            name='ReporteDesempeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('contenido_json', models.JSONField(blank=True, default=dict)),
                ('ruta_archivo', models.TextField(blank=True)),
                ('incluye_datos_sensibles', models.BooleanField(default=False)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('intento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.intento')),
            ],
            options={
                'db_table': 'reportes_desempeno',
            },
        ),
        migrations.CreateModel(
            name='RespuestaDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justificacion', models.TextField(blank=True)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('confirmada', models.BooleanField(default=True)),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.decision')),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.escena')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simulador.intento')),
            ],
            options={
                'db_table': 'respuestas_decisiones',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resumen', models.TextField()),
                ('aciertos', models.TextField(blank=True)),
                ('errores', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('indicadores_json', models.JSONField(blank=True, default=dict)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulador.intento')),
            ],
            options={
                'db_table': 'retroalimentaciones',
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rubricas',
            },
        ),
        migrations.AddField(
            model_name='evaluacionintento',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.rubrica'),
        ),
        migrations.AddField(
            model_name='criteriorubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='simulador.rubrica'),
        ),
        migrations.CreateModel(
            name='CasoTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.caso')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.tematica')),
            ],
            options={
                'db_table': 'casos_tematicas',
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='tematicas',
            field=models.ManyToManyField(blank=True, through='simulador.CasoTematica', to='simulador.tematica'),
        ),
        migrations.CreateModel(
            name='UsoHerramientaIntento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datos_entrada_json', models.JSONField(blank=True, default=dict)),
                ('resultado_json', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('usada_en', models.DateTimeField(auto_now_add=True)),
                ('escena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulador.escena')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.herramientaprofesional')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.intento')),
            ],
            options={
                'db_table': 'uso_herramientas_intento',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('INICIO_SESION', 'Inicio de sesion'), ('CIERRE_SESION', 'Cierre de sesion'), ('CREACION', 'Creacion'), ('ACTUALIZACION', 'Actualizacion'), ('ELIMINACION_LOGICA', 'Eliminacion logica'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('EXPORTACION', 'Exportacion'), ('CONSULTA_IA', 'Consulta IA'), ('ACCESO_DENEGADO', 'Acceso denegado')], max_length=40)),
                ('entidad', models.CharField(blank=True, max_length=120)),
                ('entidad_id', models.UUIDField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_eventos',
                'indexes': [models.Index(fields=['usuario'], name='auditoria_e_usuario_bccae5_idx'), models.Index(fields=['tipo_evento'], name='auditoria_e_tipo_ev_b8e64d_idx'), models.Index(fields=['entidad', 'entidad_id'], name='auditoria_e_entidad_8d67ed_idx'), models.Index(fields=['creado_en'], name='auditoria_e_creado__03bf06_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asignacioncaso',
            index=models.Index(fields=['caso'], name='asignacione_caso_id_0edf97_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncaso',
            index=models.Index(fields=['grupo'], name='asignacione_grupo_i_b2fe81_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncaso',
            index=models.Index(fields=['estudiante'], name='asignacione_estudia_60ea7c_idx'),
        ),
        migrations.AddIndex(
            model_name='actorcaso',
            index=models.Index(fields=['caso'], name='actores_cas_caso_id_725a45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casocompetencia',
            unique_together={('caso', 'competencia')},
        ),
        migrations.AlterUniqueTogether(
            name='decisioncompetencia',
            unique_together={('decision', 'competencia')},
        ),
        migrations.AddIndex(
            model_name='escena',
            index=models.Index(fields=['caso'], name='escenas_caso_id_c9ae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='escena',
            index=models.Index(fields=['tipo'], name='escenas_tipo_ff7e9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='escena',
            unique_together={('caso', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['escena_origen'], name='decisiones_escena__d94b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['escena_destino'], name='decisiones_escena__238049_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casoetiqueta',
            unique_together={('caso', 'etiqueta')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacioncriterio',
            unique_together={('evaluacion', 'criterio')},
        ),
        migrations.AddIndex(
            model_name='herramientaprofesional',
            index=models.Index(fields=['activa'], name='herramienta_activa_b9bfe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='herramientaporcaso',
            unique_together={('caso', 'herramienta', 'escena')},
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['estudiante'], name='intentos_estudia_7a0c24_idx'),
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['caso'], name='intentos_caso_id_631094_idx'),
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['estado'], name='intentos_estado_8a048a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intento',
            unique_together={('estudiante', 'caso', 'numero_intento')},
        ),
        migrations.AlterUniqueTogether(
            name='recursocaso',
            unique_together={('recurso', 'caso')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestadecision',
            unique_together={('intento', 'escena', 'decision')},
        ),
        migrations.AlterUniqueTogether(
            name='casotematica',
            unique_together={('caso', 'tematica')},
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['estado'], name='casos_estado_8ec440_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['nivel'], name='casos_nivel_30b4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['creado_por'], name='casos_creado__320721_idx'),
        ),
    ]
