# Generated by Django 6.0.6 on 2026-06-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertadesempeno',
            name='tipo',
            field=models.CharField(choices=[('BAJO_DESEMPENO', 'Bajo desempeño'), ('EVENTO_CRITICO', 'Evento crítico'), ('RIESGO_ALTO', 'Riesgo alto'), ('INACTIVIDAD', 'Inactividad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoriaevento',
            name='tipo_evento',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('CIERRE_SESION', 'Cierre de sesión'), ('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('ELIMINACION_LOGICA', 'Eliminación lógica'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('EXPORTACION', 'Exportación'), ('CONSULTA_IA', 'Consulta IA'), ('ACCESO_DENEGADO', 'Acceso denegado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nivel',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='escena',
            name='tipo',
            field=models.CharField(choices=[('INTRODUCCION', 'Introducción'), ('DESARROLLO', 'Desarrollo'), ('DECISION', 'Decisión'), ('USO_HERRAMIENTA', 'Uso de herramienta'), ('RETROALIMENTACION', 'Retroalimentación'), ('FINAL', 'Final')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('TEORIA', 'Teoría'), ('GUIA', 'Guía'), ('LECTURA', 'Lectura'), ('VIDEO', 'Video'), ('INSTRUMENTO', 'Instrumento'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
